# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "rhel" do |rhel|
    rhel.vm.box = "bento/centos-7.2"
    rhel.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.name = "RHEL NGINX"
    end

    rhel.vm.network "forwarded_port", guest: 80, host: 81
    rhel.vm.provision "shell", path: "bin/httpd"
  end
end
