# Check if name exists
- name: Check master record
  set_fact:
    masterdns: "{{ lookup('dig','master.{{ec2env}}{{dnsprefix}}.{{dnszone}}')}}"

- name: Remove Master DNS entries
  route53:
    state: absent
    zone: "{{ dnszone }}"
    record: "master.{{ec2env}}.{{dnsprefix}}.{{ dnszone }}"
    type: A
    ttl: 60
    value:
      - "{{ groups['kubemaster'][0] }}"
  when: masterdns != "NXDOMAIN"

- name: Check controller record
  set_fact:
    controllerdns: "{{ lookup('dig','control.{{ec2env}}.{{dnsprefix}}.{{dnszone}}')}}"
  register: controllerdns

- name: Remove Controller DNS entries
  route53:
    state: absent
    zone: "{{ dnszone }}"
    record: "control.{{ec2env}}.{{dnsprefix}}.{{ dnszone }}"
    type: A
    ttl: 60
    value:
      - "{{ groups['controller'][0] }}"
  when: controllerdns != "NXDOMAIN"
