# Check if name exists
- name: Check master record
  set_fact:
    masterdns: "{{ lookup('dig','master.{{dnsname}}')}}"

- name: Remove Master DNS entries
  route53:
    state: absent
    zone: "{{ dnszone }}"
    record: "master.{{dnsname}}"
    type: A
    ttl: 60
    value:
      - "{{ groups['kubemaster'][0] }}"
  when: masterdns != "NXDOMAIN"

- name: Check controller record
  set_fact:
    controllerdns: "{{ lookup('dig','control.{{dnsname}}')}}"
  register: controllerdns

- name: Remove Controller DNS entries
  route53:
    state: absent
    zone: "{{ dnszone }}"
    record: "control.{{dnsname}}"
    type: A
    ttl: 60
    value:
      - "{{ groups['controller'][0] }}"
  when: controllerdns != "NXDOMAIN"
