#!/bin/bash

# Check if we're debugging
if [[ $1 != DEBUG ]] && [[ $1 != SKIP ]]
then
	sshKeyFile="$1"
else
	sshKeyFile="$2"
fi

# Check if the key file supplied exists
if [[ ! -e $sshKeyFile ]] || [[ -z $sshKeyFile ]]
then
	echo "SSH Key file $sshKeyFile does not exist, or not supplied" 1>&2
	echo "SYNTAX: $0 [DEBUG] sshKeyFile"
	exit 1
fi

if [[ $1 != SKIP ]]
then
	if [[ $1 == DEBUG ]]
	then
		ansible-playbook -vvvv -i environments/prod --extra-vars "ansible_ssh_private_key_file=$sshKeyFile" create.yml
	else
		ansible-playbook -i environments/prod --extra-vars "ansible_ssh_private_key_file=$sshKeyFile" create.yml
	fi
fi

if (( $? == 0 ))
then
		# Install Kubernetes on to the cluster and use the Public IP of the Master for access ip
		ssh -i $sshKeyFile ec2-user@$(grep -A1 '^\[controller' environments/prod/hosts  | tail -1 | awk '{print $1}') "cd kubespray; ansible-playbook -i inventory/mycluster/inventory.ini --become --become-user=root cluster.yml"
		# For insecure registry;
		# --extra-vars "docker_options=--insecure-registry=xxx.yyy:5000"
		# Add a DNS LB to the cluster and DNS name with wild card for the apps
		if [[ $? == 0 ]]
		then
			ansible-playbook -i environments/prod --extra-vars "ansible_ssh_private_key_file=$sshKeyFile" addlb.yml
		fi
fi
