#!/bin/bash

# Check if we're debugging
if [[ $1 != DEBUG ]] && [[ $1 != SKIP ]]
then
	sshKeyFile="$1"
else
	sshKeyFile="$2"
fi

# Check if the key file supplied exists
if [[ ! -e $sshKeyFile ]] || [[ -z $sshKeyFile ]]
then
	echo "SSH Key file $sshKeyFile does not exist, or not supplied" 1>&2
	echo "SYNTAX: $0 [DEBUG] sshKeyFile"
	exit 1
fi

if [[ $1 != SKIP ]]
then
	if [[ $1 == DEBUG ]]
	then
		ansible-playbook -vvvv -i environments/prod --extra-vars "ansible_ssh_private_key_file=$sshKeyFile" create.yml
	else
		ansible-playbook -i environments/prod --extra-vars "ansible_ssh_private_key_file=$sshKeyFile" create.yml
	fi
else
	if (( $? == 0 ))
	then
		ssh -i $sshKeyFile ec2-user@$(grep -A1 '^\[controller' environments/prod/hosts  | tail -1 | awk '{print $1}') "cd kubespray; ansible-playbook -i inventory/mycluster/inventory.ini --become --become-user=root cluster.yml"
	fi
fi
