#!/bin/bash

#description: Petclinic application
#chkconfig: 2345 99 99

case $1 in
  start)
    cd /opt/petclinic
    java -jar *.jar &
    ;;
  stop)
    kill $(ps -ef | grep petclininc | grep -v grep | awk '{print $2}')
    ;;
  status)
    ps -ef | grep petclinic | grep -v grep
    ;;
esac
